name: publish Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@amboss-mededu'
      - run: npm ci
      - run: |
          git config user.email "alexjeffcott@gmail.com"
          git config user.name "alexjeffcott"
      - run: npm version patch
      - run: git push --tags && git push
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.AJT_PAT_AMBOSS_BROWSER_EXTENSION}}
